import type { Artist, Beat, SiteSettings, Track } from "@/types";

export const siteSettings: SiteSettings = {
  title: "HamloProd",
  subtitle: "Ты ещё вернёшься",
  archiveHeadline: "Archive Case Files",
  archiveDescription:
    "Select a beat from the archives. Final content will come from Supabase, not from page code.",
};

export const mockBeats: Beat[] = [
  {
    id: "beat-001",
    title: "Dorothy's Abortion",
    slug: "dorothys-abortion",
    caseNumber: "CASE-001",
    coverPalette: "from-stone-700 via-stone-900 to-zinc-950",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 87,
    mood: "Boom Bap / Dark",
    description: "Dusty room tone, restrained low end and a tape-aged drum pocket.",
    priceUsd: 100,
    status: "available",
    featured: true,
    createdAt: "2026-04-01T10:00:00.000Z",
    duration: "02:32",
  },
  {
    id: "beat-002",
    title: "Lost City Lights",
    slug: "lost-city-lights",
    caseNumber: "CASE-002",
    coverPalette: "from-slate-500 via-slate-800 to-zinc-950",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 96,
    mood: "Wavy / Atmospheric",
    description: "A late-night skyline piece with submerged chords and slow neon movement.",
    priceUsd: 75,
    status: "reserved",
    featured: false,
    createdAt: "2026-04-02T10:00:00.000Z",
    duration: "02:45",
  },
  {
    id: "beat-003",
    title: "Shadow Walker",
    slug: "shadow-walker",
    caseNumber: "CASE-003",
    coverPalette: "from-amber-900 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 140,
    mood: "Dark Trap",
    description: "Sparse bells, pressure-heavy kicks and an alleyway atmosphere.",
    priceUsd: 150,
    status: "available",
    featured: false,
    createdAt: "2026-04-03T10:00:00.000Z",
    duration: "02:18",
  },
  {
    id: "beat-004",
    title: "Neon Dreams",
    slug: "neon-dreams",
    caseNumber: "CASE-004",
    coverPalette: "from-orange-800 via-rose-900 to-zinc-950",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 90,
    mood: "Synthwave",
    description: "Street reflections, warm pads and a relaxed city pulse.",
    priceUsd: 80,
    status: "private",
    featured: false,
    createdAt: "2026-04-04T10:00:00.000Z",
    duration: "03:01",
  },
  {
    id: "beat-005",
    title: "Cold Memories",
    slug: "cold-memories",
    caseNumber: "CASE-005",
    coverPalette: "from-zinc-400 via-stone-700 to-zinc-950",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 78,
    mood: "Sad / Chill",
    description: "Frozen ambience with patient drums and a very open top line.",
    priceUsd: 65,
    status: "available",
    featured: true,
    createdAt: "2026-04-05T10:00:00.000Z",
    duration: "02:58",
  },
  {
    id: "beat-006",
    title: "Ruthless Night",
    slug: "ruthless-night",
    caseNumber: "CASE-006",
    coverPalette: "from-red-900 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    previewStoragePath: null,
    wavFilePath: null,
    zipFilePath: null,
    bpm: 132,
    mood: "Hard / Aggressive",
    description: "Sharp percussion, siren-like textures and red-lit pressure.",
    priceUsd: 50,
    status: "sold",
    featured: true,
    createdAt: "2026-04-06T10:00:00.000Z",
    duration: "02:24",
  },
];

export const mockTracks: Track[] = [
  {
    id: "track-001",
    title: "No Exit",
    slug: "no-exit",
    artistName: "HaM",
    coverPalette: "from-zinc-800 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2025-11-14",
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "track-002",
    title: "Grey Season",
    slug: "grey-season",
    artistName: "HaM",
    coverPalette: "from-stone-700 via-zinc-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2025-09-02",
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "track-003",
    title: "Last Hallway",
    slug: "last-hallway",
    artistName: "HaM",
    coverPalette: "from-amber-950 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2024-12-20",
    createdAt: "2026-04-03T10:00:00.000Z",
  },
];

export const mockArtists: Artist[] = [
  {
    id: "artist-001",
    artistName: "Mira Vale",
    trackTitle: "Downstairs Smoke",
    beatTitle: "Lost City Lights",
    coverPalette: "from-slate-700 via-zinc-900 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "artist-002",
    artistName: "Kane Mercer",
    trackTitle: "Floodlights",
    beatTitle: "Ruthless Night",
    coverPalette: "from-red-950 via-zinc-900 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "artist-003",
    artistName: "Nina Grey",
    trackTitle: "Snow Under Neon",
    beatTitle: "Cold Memories",
    coverPalette: "from-stone-500 via-zinc-800 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    createdAt: "2026-04-03T10:00:00.000Z",
  },
];