import type { Artist, ArtistPost, Comment, Post, Release, SiteSettings, Track } from "@/types";

export const siteSettings: SiteSettings = {
  title: "HamloProd",
  subtitle: "Ты ещё вернёшься",
  archiveHeadline: "Archive Case Files",
  archiveDescription:
    "Select a beat from the archives.",
};

export const mockTracks: Track[] = [
  {
    id: "track-001",
    title: "No Exit",
    slug: "no-exit",
    artistName: "HaM",
    coverPalette: "from-zinc-800 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2025-11-14",
    releaseId: null,
    trackNumber: null,
    isDemo: false,
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "track-002",
    title: "Grey Season",
    slug: "grey-season",
    artistName: "HaM",
    coverPalette: "from-stone-700 via-zinc-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2025-09-02",
    releaseId: "release-001",
    trackNumber: 1,
    isDemo: false,
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "track-003",
    title: "Last Hallway",
    slug: "last-hallway",
    artistName: "HaM",
    coverPalette: "from-amber-950 via-stone-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    mp3FilePath: null,
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    releaseDate: "2024-12-20",
    releaseId: "release-001",
    trackNumber: 2,
    isDemo: false,
    createdAt: "2026-04-03T10:00:00.000Z",
  },
];

export const mockReleases: Release[] = [
  {
    id: "release-001",
    title: "Grey Season EP",
    slug: "grey-season-ep",
    artistName: "HaM",
    releaseType: "ep",
    coverPalette: "from-stone-700 via-zinc-900 to-black",
    coverImageUrl: null,
    coverImagePath: null,
    description: "Дебютный EP HaM Hamilio — атмосферный проект о смене сезонов.",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    featArtistNames: "",
    releaseDate: "2025-09-02",
    published: true,
    featured: false,
    createdAt: "2026-04-02T10:00:00.000Z",
    updatedAt: "2026-04-02T10:00:00.000Z",
    tracks: [
      { id: "track-002", title: "Grey Season", slug: "grey-season", trackNumber: 1, mp3FilePath: null, createdAt: "2026-04-02T10:00:00.000Z" },
      { id: "track-003", title: "Last Hallway", slug: "last-hallway", trackNumber: 2, mp3FilePath: null, createdAt: "2026-04-03T10:00:00.000Z" },
    ],
  },
];

export const mockArtists: Artist[] = [
  {
    id: "artist-001",
    slug: "mira-vale",
    artistName: "Mira Vale",
    trackTitle: "Downstairs Smoke",
    beatTitle: "Lost City Lights",
    bio: "Независимый исполнитель из Москвы. Смешивает атмосферный хип-хоп с современными электронными текстурами.",
    photoUrl: null,
    photoPath: null,
    coverPalette: "from-slate-700 via-zinc-900 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    vkUrl: "",
    telegramUrl: "",
    yandexMusicUrl: "",
    tidalUrl: "",
    soundcloudUrl: "",
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "artist-002",
    slug: "kane-mercer",
    artistName: "Kane Mercer",
    trackTitle: "Floodlights",
    beatTitle: "Ruthless Night",
    bio: "Продюсер и лирик. Тёмный саунд, острые тексты.",
    photoUrl: null,
    photoPath: null,
    coverPalette: "from-red-950 via-zinc-900 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    vkUrl: "",
    telegramUrl: "",
    yandexMusicUrl: "",
    tidalUrl: "",
    soundcloudUrl: "",
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "artist-003",
    slug: "nina-grey",
    artistName: "Nina Grey",
    trackTitle: "Snow Under Neon",
    beatTitle: "Cold Memories",
    bio: "Меланхоличный R&B и атмосферный поп на стыке жанров.",
    photoUrl: null,
    photoPath: null,
    coverPalette: "from-stone-500 via-zinc-800 to-black",
    spotifyUrl: "https://open.spotify.com/",
    appleMusicUrl: "https://music.apple.com/",
    youtubeUrl: "https://youtube.com/",
    vkUrl: "",
    telegramUrl: "",
    yandexMusicUrl: "",
    tidalUrl: "",
    soundcloudUrl: "",
    createdAt: "2026-04-03T10:00:00.000Z",
  },
];

export const mockArtistPosts: ArtistPost[] = [];
export const mockComments: Comment[] = [];

export const mockPosts: Post[] = [
  {
    id: "post-001",
    title: "Drum Generator VST3 — первый анонс",
    slug: "drum-generator-vst3-first-look",
    excerpt: "Новый VST3-сектор открыт. Здесь будут новости, обновления, демо и документация по инструменту.",
    content:
      "Мы открываем отдельную витрину для Drum Generator VST3.\n\nТеперь новости и материалы по инструменту можно публиковать прямо из админки, без ручного редактирования страниц.\n\nПиши посты на русском — английская версия для EN-режима будет формироваться автоматически.",
    category: "news",
    section: "vst",
    coverPalette: "from-amber-900 via-stone-900 to-black",
    ctaLabel: "Скоро демо",
    ctaUrl: null,
    published: true,
    featured: true,
    createdAt: "2026-04-20T10:00:00.000Z",
    updatedAt: "2026-04-20T10:00:00.000Z",
  },
];
