export const BASE_STYLE = [
  "body{margin:0;padding:40px 32px;font-family:'IBM Plex Mono',monospace,'Courier New';",
  "background:#fff;color:#111;font-size:13px;line-height:1.8}",
  "h1{font-size:16px;text-transform:uppercase;letter-spacing:.18em;margin:0 0 6px}",
  "h2{font-size:13px;text-transform:uppercase;letter-spacing:.14em;margin:28px 0 8px;",
  "border-bottom:1px solid #ccc;padding-bottom:4px}",
  ".meta{color:#555;font-size:11px;letter-spacing:.1em;margin-bottom:32px}",
  "table{width:100%;border-collapse:collapse;margin-bottom:20px}",
  "td{padding:6px 8px;border:1px solid #ccc;vertical-align:top;font-size:12px}",
  "td:first-child{white-space:nowrap;color:#555;width:42%}",
  ".clause{margin-bottom:14px}",
  ".clause strong{display:block;text-transform:uppercase;font-size:11px;",
  "letter-spacing:.14em;margin-bottom:4px}",
  ".signatures{margin-top:48px;display:flex;gap:60px}",
  ".sig-block{flex:1}",
  ".sig-line{border-bottom:1px solid #111;margin-top:32px;margin-bottom:4px}",
  ".sig-label{font-size:11px;color:#555;letter-spacing:.1em}",
  "@media print{body{padding:20px}}",
].join("");
